FROM node:20.15-alpine AS base

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json .
COPY . .
RUN npm install

# Build app
RUN npm run build
ENV NODE_ENV production
ENV PORT 4000
EXPOSE $PORT

CMD ["npm", "run", "start"]