FROM node:20.15-alpine AS base

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json .
COPY . .
RUN npm install

# Build app
ENV NODE_ENV development
ENV PORT 3000
EXPOSE $PORT

CMD ["npm", "run", "dev"]