version: '3.9'
services:
  webdev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    env_file:
      - .env.local
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: src
          target: /app/src
          ignore:
            - node_modules/
            - .git/
            - .next/
        - action: rebuild
          path: package.json
  webprod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    working_dir: /app
    ports:
      - '4000:4000'
    env_file:
      - .env
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: berlian_motor
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

networks:
  berlian_motor_network:
    driver: bridge
